flags:
  urlist:
    library-only: false
    dev: false
packages:
- '.'
- location:
    git: https://github.com/myShoggoth/shakespeare.git
    commit: 56c05657d5fdb48584cb1faf537f6891f67400c4
extra-deps: []
resolver: lts-2.14
