Default: &defaults
  database: urlist.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: urlist_test.sqlite3
  <<: *defaults

Staging:
  database: urlist_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: urlist_production.sqlite3
  poolsize: 100
  <<: *defaults
